### ISSUE TITLE
반응형 웹디자인

### ISSUE THREAD

**Issue by litsynp** [hyunsooklm/Opensource_PlantUml#10]
현재 React 서버를 이용해 프론트엔드 웹페이지를 들어가서 창의 크기를 줄이면 Convert, 텍스트 구조 등이 전부 깨진다. 사이즈의 크기에 따라 비례해서 크기를 줄일 수 있도록 수정해야함.

**Comment by cauminam** [comment]
I pushed improved version on deact branch. please check :)

now depending on the size of the web window, the screen is not broken according to the ratio.
