### ISSUE TITLE
로고/마스코트 디자인

### ISSUE THREAD

**Issue by litsynp** [hyunsooklm/Opensource_PlantUml#11]
로고 또는 마스코트를 디자인하는 게 좋을 것 같다.
'TTUM'이라는 글자를 이용하여 깔끔한 이미지 또는 아이콘을 만들어주는 프로그램을 사용하면 좋을 것 같다.

**Comment by cauminam** [comment]
<img width="657" alt="스크린샷 2020-06-14 오전 3 54 23" src="https://user-images.githubusercontent.com/55436989/84578725-fd3ca880-ae02-11ea-9476-0bcf476b29e8.png">
<img width="655" alt="스크린샷 2020-06-14 오전 3 54 36" src="https://user-images.githubusercontent.com/55436989/84578727-ff9f0280-ae02-11ea-9273-cc8aab443d87.png">
<img width="654" alt="스크린샷 2020-06-14 오전 3 54 49" src="https://user-images.githubusercontent.com/55436989/84578728-00d02f80-ae03-11ea-845e-daa941dd5672.png">
<img width="658" alt="스크린샷 2020-06-14 오전 3 55 06" src="https://user-images.githubusercontent.com/55436989/84578729-02015c80-ae03-11ea-9490-9836d89cd42f.png">
<img width="657" alt="스크린샷 2020-06-14 오전 3 55 46" src="https://user-images.githubusercontent.com/55436989/84578730-0299f300-ae03-11ea-878a-6d9643de860e.png">
<img width="658" alt="스크린샷 2020-06-14 오전 3 55 57" src="https://user-images.githubusercontent.com/55436989/84578731-03328980-ae03-11ea-866c-288bcc8c57eb.png">
<img width="658" alt="스크린샷 2020-06-14 오전 3 56 06" src="https://user-images.githubusercontent.com/55436989/84578732-03cb2000-ae03-11ea-97ae-a2b82a1804d6.png">
<img width="660" alt="스크린샷 2020-06-14 오전 3 56 14" src="https://user-images.githubusercontent.com/55436989/84578735-0463b680-ae03-11ea-943d-a79d5781eb89.png">
<img width="659" alt="스크린샷 2020-06-14 오전 3 56 32" src="https://user-images.githubusercontent.com/55436989/84578736-04fc4d00-ae03-11ea-8f76-ae623557a8e1.png">
<img width="657" alt="스크린샷 2020-06-14 오전 3 57 52" src="https://user-images.githubusercontent.com/55436989/84578738-062d7a00-ae03-11ea-901d-a8e1bff3f1e6.png">
<img width="656" alt="스크린샷 2020-06-14 오전 3 58 03" src="https://user-images.githubusercontent.com/55436989/84578739-06c61080-ae03-11ea-9c27-7e353a8afc73.png">
<img width="660" alt="스크린샷 2020-06-14 오전 3 58 13" src="https://user-images.githubusercontent.com/55436989/84578740-06c61080-ae03-11ea-9e90-fe8b4c9da4ea.png">
<img width="655" alt="스크린샷 2020-06-14 오전 3 59 13" src="https://user-images.githubusercontent.com/55436989/84578741-09286a80-ae03-11ea-9855-9e33993f1ee9.png">
<img width="657" alt="스크린샷 2020-06-14 오전 3 59 39" src="https://user-images.githubusercontent.com/55436989/84578742-0af22e00-ae03-11ea-9e6e-773a87c293bd.png">
<img width="499" alt="스크린샷 2020-06-14 오전 4 09 14" src="https://user-images.githubusercontent.com/55436989/84578743-0b8ac480-ae03-11ea-8af7-bef648533957.png">
