### ISSUE TITLE
when make imagefile

### ISSUE THREAD

**Issue by hyunsooklm** [hyunsooklm/Opensource_PlantUml#12]
Why all circumstances are in checkout?
Why all actor-(usecase) are in checkout?
we must fix it. But...

Cause we have no enough time. so How about receive in server one word. situation? from User.
thanks.

**Comment by litsynp** [comment]
This issue is fixed in commit 5c282f9f2b8ac23cecd9e9cd5a0e4923c1781d79, by changing `checkout` to `system`, instead.
